Repository python-virtualenvwrapper/virtualenvwrapper, pull requests merged in 2023-01, with the labels that each got.

#18 add pkglint test and fix some warnings
  .github/workflows/test.yml
  setup.cfg
  tox.ini
Labels: CI

#21 updates to make CI jobs pass
  docs/source/command_ref.rst
  docs/source/developers.rst
  tests/run_tests
  tests/setup.sh
  tests/test_cp.sh
  tests/test_lazy_loaded.sh
  tests/test_ls.sh
  tests/test_mktmpenv.sh
  tests/test_mkvirtualenv.sh
  tests/test_run_hook.sh
  tests/test_tempfile.sh
  tests/test_toggleglobalsitepackages.sh
  tests/test_wipeenv.sh
  tox.ini
  virtualenvwrapper.sh
Labels: documentation, CI

#24 require at least one reviewer to approve PRs
  .mergify.yml
Labels: Mergify

#20 Updating references to bitbucket
  README.es.rst
  README.ja.rst
  README.txt
  docs/source/developers.rst
  docs/source/extensions.rst
  docs/source/index.rst
  docs/source/install.rst
  docs/source/plugins.rst
  docs/source/projects.rst
Labels: documentation

#29 mergify: add rules to label PRs based on pbr sem-ver data
  .mergify.yml
Labels: Mergify

#27 drop ksh support
  README.txt
  docs/source/install.rst
  docs/source/plugins.rst
  tests/run_tests
  tests/test_dir_stack.sh
  tox.ini
  virtualenvwrapper.sh
Labels: documentation, CI, breaking change

#28 remove python2 from startup logic for finding the python interpreter
  virtualenvwrapper.sh
Labels: breaking change

#30 tox: update doc build commands
  docs/source/command_ref.rst
  docs/source/developers.rst
  docs/source/plugins.rst
  docs/source/tips.rst
  setup.cfg
  tox.ini
Labels: documentation, CI
