Repository python-virtualenvwrapper/virtualenvwrapper, pull requests merged in 2023-12, with the labels that each got.

#83 Fixed broken link in install docs.
  docs/source/install.rst
Labels: documentation

#85 add python 3.12 to test matrix
  .github/workflows/test.yml
  .mergify.yml
  pyproject.toml
Labels: Mergify

#88 set up automatic approval rules for mergify
  .mergify.yml
Labels: Mergify

#89 fix action-based package publishing
  .github/workflows/python-publish.yaml
  pyproject.toml
  tox.ini
Labels: CI, automatic-merge

#90 test python 3.12 on macos
  .github/workflows/test.yml
  .mergify.yml
Labels: Mergify, automatic-merge

#91 update release notes for 6.0.0.0a5
  docs/source/history.rst
Labels: documentation, automatic-merge

#92 update test declaration in readme
  README.txt
Labels: automatic-merge
