Repository python-virtualenvwrapper/virtualenvwrapper, pull requests merged in 2024-10, with the labels that each got.

#110 remove hyperlink to msys project page
  docs/source/install.rst
Labels: documentation, automatic-merge

#111 Move link check out of main doc build job
  docs/source/install.rst
  tox.ini
Labels: documentation, CI, automatic-merge

#109 Update mkvirtualenv help to document -p/--python option
  docs/source/install.rst
  virtualenvwrapper.sh
Labels: documentation
